# Generated by Django 3.1.4 on 2022-03-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('Enquiryid', models.IntegerField(primary_key=True, serialize=False)),
                ('enquiryname', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=20)),
            ],
        ),
    ]
